# PowerShell script to help set up Stripe Test Mode environment variables
# This script will create/update your .env.local file with the proper structure

Write-Host "🧪 Stripe Test Mode Setup Script" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env.local exists
$envFile = ".env.local"
$envExists = Test-Path $envFile

if ($envExists) {
    Write-Host "⚠️  .env.local already exists. This script will add/update Stripe variables." -ForegroundColor Yellow
    Write-Host "    Existing variables will be preserved." -ForegroundColor Yellow
    Write-Host ""
} else {
    Write-Host "✅ Creating new .env.local file..." -ForegroundColor Green
}

Write-Host "📋 Please provide your Stripe Test Mode credentials:" -ForegroundColor Cyan
Write-Host ""

# Get Test Mode Publishable Key
$publishableKey = Read-Host "Enter your Test Mode Publishable Key (pk_test_...)"
if (-not $publishableKey.StartsWith("pk_test_")) {
    Write-Host "⚠️  Warning: Key doesn't start with 'pk_test_'. Make sure you're using Test Mode!" -ForegroundColor Yellow
}

# Get Test Mode Secret Key
$secretKey = Read-Host "Enter your Test Mode Secret Key (sk_test_...)"
if (-not $secretKey.StartsWith("sk_test_")) {
    Write-Host "⚠️  Warning: Key doesn't start with 'sk_test_'. Make sure you're using Test Mode!" -ForegroundColor Yellow
}

# Get Test Mode Price ID
$priceId = Read-Host "Enter your Test Mode Price ID (price_...)"
if (-not $priceId.StartsWith("price_")) {
    Write-Host "⚠️  Warning: Price ID doesn't start with 'price_'. Please verify!" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "📝 Updating .env.local file..." -ForegroundColor Cyan

# Read existing .env.local if it exists
$envContent = @()
if ($envExists) {
    $envContent = Get-Content $envFile
    # Remove existing Stripe variables
    $envContent = $envContent | Where-Object {
        $_ -notmatch "^NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=" -and
        $_ -notmatch "^STRIPE_SECRET_KEY=" -and
        $_ -notmatch "^NEXT_PUBLIC_STRIPE_PRO_PRICE_ID=" -and
        $_ -notmatch "^STRIPE_WEBHOOK_SECRET=" -and
        $_ -notmatch "^# Stripe"
    }
}

# Add Stripe configuration
$stripeConfig = @"
# Stripe Test Mode Configuration
# Generated by setup-stripe-test-mode.ps1
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$publishableKey
STRIPE_SECRET_KEY=$secretKey
NEXT_PUBLIC_STRIPE_PRO_PRICE_ID=$priceId

"@

# Combine content
$newContent = $envContent + $stripeConfig

# Write to file
$newContent | Set-Content $envFile -Encoding UTF8

Write-Host "✅ .env.local file updated successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Next Steps:" -ForegroundColor Cyan
Write-Host "   1. Set the same environment variables in Firebase Functions" -ForegroundColor White
Write-Host "   2. Restart your dev server: npm run dev" -ForegroundColor White
Write-Host "   3. Test at: http://localhost:3002/pricing" -ForegroundColor White
Write-Host ""
Write-Host "📚 See STRIPE_TEST_MODE_SETUP_NOW.md for detailed instructions" -ForegroundColor Cyan


