'use client';

import { Button } from '@/components/ui/button';
import { Mail } from 'lucide-react';
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isWeekend } from 'date-fns';
import { DailyTrackingData } from '@/types/provider-wrvu-tracking';
import { formatDateString, type DateString } from '@/lib/utils/calendar-helpers';

interface WRVUTrackingActionsProps {
  currentDate: Date;
  dailyData: Record<DateString, DailyTrackingData>;
  providerName?: string;
  specialty?: string;
  onEmailReport?: () => void;
}

export function WRVUTrackingActions({
  currentDate,
  dailyData,
  providerName,
  specialty,
  onEmailReport,
}: WRVUTrackingActionsProps) {
  const handleEmailReport = () => {
    if (onEmailReport) {
      onEmailReport();
      return;
    }

    const monthStart = startOfMonth(currentDate);
    const monthEnd = endOfMonth(currentDate);
    const monthDays = eachDayOfInterval({ start: monthStart, end: monthEnd });

    // Calculate monthly stats
    let totalPatients = 0;
    let totalWRVUs = 0;
    let daysWithData = 0;
    let workingDays = 0;

    monthDays.forEach((day) => {
      const dateStr = formatDateString(day);
      const isWeekendDay = isWeekend(day);
      
      if (!isWeekendDay) {
        workingDays++;
      }

      const data = dailyData[dateStr];
      if (data && (data.patients > 0 || data.workRVUs > 0)) {
        daysWithData++;
        totalPatients += data.patients || 0;
        totalWRVUs += data.workRVUs || 0;
      }
    });

    const avgPatientsPerDay = daysWithData > 0 ? totalPatients / daysWithData : 0;
    const avgWRVUsPerDay = daysWithData > 0 ? totalWRVUs / daysWithData : 0;
    const avgWRVUsPerPatient = totalPatients > 0 ? totalWRVUs / totalPatients : 0;

    const formatNumber = (value: number, decimals: number = 0) =>
      new Intl.NumberFormat('en-US', {
        maximumFractionDigits: decimals,
        minimumFractionDigits: value % 1 === 0 ? 0 : decimals,
      }).format(value);

    const monthName = format(currentDate, 'MMMM yyyy');

    // Build email subject
    const subject = encodeURIComponent(`Provider Work RVU Tracking Report - ${monthName}`);

    // Build email body
    const emailBody = encodeURIComponent(`Provider Work RVU Tracking Report
Generated: ${new Date().toLocaleDateString()}

═══════════════════════════════════════════════════════
PROVIDER INFORMATION
═══════════════════════════════════════════════════════

${providerName ? `Provider Name: ${providerName}` : 'Provider Name: Not specified'}
${specialty ? `Specialty: ${specialty}` : 'Specialty: Not specified'}

═══════════════════════════════════════════════════════
MONTHLY SUMMARY - ${monthName.toUpperCase()}
═══════════════════════════════════════════════════════

Total Patients: ${formatNumber(totalPatients)}
Total Work RVUs: ${formatNumber(totalWRVUs, 2)}
Days with Data: ${daysWithData}
Working Days: ${workingDays}

═══════════════════════════════════════════════════════
AVERAGES
═══════════════════════════════════════════════════════

Average Patients per Day: ${formatNumber(avgPatientsPerDay, 1)}
Average wRVUs per Day: ${formatNumber(avgWRVUsPerDay, 2)}
Average wRVUs per Patient: ${formatNumber(avgWRVUsPerPatient, 2)}

═══════════════════════════════════════════════════════
DAILY BREAKDOWN
═══════════════════════════════════════════════════════

${monthDays
  .filter((day) => {
    const dateStr = formatDateString(day);
    const data = dailyData[dateStr];
    return data && (data.patients > 0 || data.workRVUs > 0);
  })
  .map((day) => {
    const dateStr = formatDateString(day);
    const data = dailyData[dateStr];
    return `${format(day, 'MMM d, yyyy')}: ${data?.patients || 0} patients, ${formatNumber(data?.workRVUs || 0, 2)} wRVUs`;
  })
  .join('\n') || 'No data entered for this month.'}

═══════════════════════════════════════════════════════
Generated by CompLens™ Provider Compensation Intelligence
═══════════════════════════════════════════════════════`);

    // Open email client
    window.location.href = `mailto:?subject=${subject}&body=${emailBody}`;
  };

  return (
    <div className="flex flex-wrap items-center gap-3">
      <Button
        variant="outline"
        onClick={handleEmailReport}
        className="min-h-[44px] touch-target"
      >
        <Mail className="w-4 h-4 mr-2" />
        Email Report
      </Button>
    </div>
  );
}

